name: Jobs
on:
  workflow_dispatch:
    inputs:
      domain:
        default: 'testspace.com'
  
jobs:
  int:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: |
          touch github_run.txt
          env >> git_run.txt
          testspace git_run.txt
  this-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job}}]./testcontent/*.xml"
  that-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"                          
  job9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
  job19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"                          
  job20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: |
          echo Sleep for 30
          sleep 30
          testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
          sleep 30
  job21:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: |
          echo Sleep for 30
          sleep 30
          testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
          sleep 30
  job22:
    runs-on: ubuntu-latest
    needs: [job20, job21]
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"         