name: Jobs
on:
  workflow_dispatch:
    inputs:
      domain:
        default: 'testspace.com'
  
jobs:
  int:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: |
          touch github_run.txt
          env >> git_run.txt
          testspace git_run.txt                    
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: |
          echo Sleep for 30
          testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
          sleep 30
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: |
          echo Sleep for 30
          testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"
          sleep 30
  job22:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      #- run: sleep 60
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job }}]./testcontent/*.xml"         