name: Matrix
on: 
  workflow_dispatch:
    inputs:
      domain:
        default: 'testspace.com'
   
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}.${{ inputs.domain}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }} / ${{ matrix.os}}]./testcontent/*.xml"
